name: CI

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  jepsen-test:
    runs-on: ubuntu-latest
    name: The simplest jepsen test for HStreamDB
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Prepare environment for test
        run: |
          cd ./docker
          ./init-secret.sh

      - name: Build base image
        run: |
          ./script/build_base.sh

      - name: Build test images (legacy)
        run: |
          ./script/build_legacy.sh
      - name: Build test images (kafka)
        run: |
          ./script/build_kafka.sh

      - name: Clean dangling images
        run: |
          docker image prune -f

      - name: Check disk space
        run: |
          df -h

      - name: Start test cluster and run jepsen test (legacy)
        run: |
          ./script/up_legacy.sh

      - name: Cleanup resources (legacy)
        run: |
          ./script/clean_legacy.sh

      - name: Start test cluster and run jepsen test (kafka)
        run: |
          ./script/up_kafka.sh

      - name: Cleanup resources (kafka)
        run: |
          ./script/clean_kafka.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        if: ${{ success() }} || ${{ failure() }}
        with:
          name: jepsen-test-result
          path: |
            store/legacy-husky
            store/legacy-list-append
            store/kafka
            /tmp/*.log
            !store/latest
            !store/current
          retention-days: 7
